### ISSUE TITLE
Starred Chips Display Issue.

### ISSUE THREAD

**Issue by Unity-Blaster** [SebLague/Digital-Logic-Sim#118] opened 2023-01-01 13:40 UTC
Un-starred chips, after re-starring, don't appear on the bottom bar. And all other chips made after that also don't appear. Only way to access them is then through the library.
![image_2023-01-01_190905950](https://user-images.githubusercontent.com/121755799/210172591-cbea9cbc-b4e4-4f32-bbbd-14bf78143429.png)
![image_2023-01-01_191007209](https://user-images.githubusercontent.com/121755799/210172629-7b8139c6-35ff-4dfe-bc3f-77f568b55e09.png)

**Quick Edit:** 

### System info:

- OS: Win 10 22H2
- Display Size: 1366x768
- RAM: 4 GB LPDDR3
- CPU: Base Clock @1.1 GHz, 2 Cores

This might be enough, but I will add more if needed.

**Comment by SebLague** [comment] 2023-01-01 14:25
Thanks for the report! I'm struggling to reproduce this bug -- if it's not too much to ask, could you list the steps needed to reproduce this starting from a blank project (or a screen capture of it)?

**Comment by rube200** [comment] 2023-01-01 22:09
@SebLague Since you may take a look into this bug can u also add something like a star to fast view stared chips

**Comment by Unity-Blaster** [comment] 2023-01-02 11:12
> Thanks for the report! I'm struggling to reproduce this bug -- if it's not too much to ask, could you list the steps needed to reproduce this starting from a blank project (or a screen capture of it)?

Sorry to inform, but I couldn't Reproduce it.
Instead I've attached it's files.
[Digital Logic Sim.zip](https://github.com/SebLague/Digital-Logic-Sim/files/10331071/Digital.Logic.Sim.zip)

**Comment by SebLague** [comment] 2023-01-02 15:11
Okay I'll take a look and see if I can figure out what went wrong, thank you.
And yes I'll look into some more options for organizing the library @rube200

**Comment by SebLague** [comment] 2023-02-05 22:47
Closing since can't reproduce

**Closed by SebLague** 2023-02-05 22:47 UTC
